 -- VHDL Entity CSELib.test_VGA.symbol
--
-- Created:
--          by - jinz.student (tachyon.cse.sc.edu)
--          at - 09:43:30 11/11/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.1 (Build 12)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY test_VGA IS
   PORT( 
      CLOCK_27  : IN     STD_LOGIC;
      KEY       : IN     std_logic_vector (3 DOWNTO 0);
      VGA_B     : OUT    std_logic_vector (9 DOWNTO 0);
      VGA_BLANK : OUT    std_logic;
      VGA_CLK   : OUT    STD_LOGIC;
      VGA_G     : OUT    std_logic_vector (9 DOWNTO 0);
      VGA_HS    : OUT    std_logic;
      VGA_R     : OUT    std_logic_vector (9 DOWNTO 0);
      VGA_SYNC  : OUT    std_logic;
      VGA_VS    : OUT    std_logic;
      TD_RESET  : OUT    std_logic
   );

-- Declarations

END test_VGA ;

--
-- VHDL Architecture CSELib.test_VGA.struct
--
-- Created:
--          by - jinz.student (tachyon.cse.sc.edu)
--          at - 09:43:30 11/11/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.1 (Build 12)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

--LIBRARY CSELib;

ARCHITECTURE struct OF test_VGA IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL mem_waddr : std_logic_vector(12 DOWNTO 0);
   SIGNAL mem_wdata : std_logic_vector(14 DOWNTO 0);
   SIGNAL mem_web   : std_logic;
   SIGNAL row       : std_logic_vector(5 DOWNTO 0);
   SIGNAL col       : std_logic_vector(6 DOWNTO 0);
   SIGNAL rst       : STD_LOGIC;


   -- Component Declarations
   COMPONENT Display_IF
   PORT (
      clk        : IN     STD_LOGIC  := '0';
      mem_waddr  : IN     std_logic_vector (12 DOWNTO 0);
      mem_wdata  : IN     std_logic_vector (14 DOWNTO 0);
      mem_web    : IN     std_logic ;
      rst        : IN     STD_LOGIC  := '0';
      VGA_B      : OUT    std_logic_vector (9 DOWNTO 0);
      VGA_BLANK  : OUT    std_logic ;
      VGA_CLK    : OUT    STD_LOGIC ;
      VGA_G      : OUT    std_logic_vector (9 DOWNTO 0);
      VGA_H_SYNC : OUT    std_logic ;
      VGA_R      : OUT    std_logic_vector (9 DOWNTO 0);
      VGA_SYNC   : OUT    std_logic ;
      VGA_V_SYNC : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   --FOR ALL : Display_IF USE ENTITY CSELib.Display_IF;
   -- pragma synthesis_on


BEGIN
  TD_RESET <= '1';

   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1                                        
   process (rst,CLOCK_27)
     begin
       
       if rst='1' then
         row <= (others=>'0');
         col <= (others=>'0');
         
       elsif rising_edge(CLOCK_27) then
         if col="1111111" then
           col <= (others=>'0');
           row <= row + "1";
         else
           col <= col + "1";
         end if;
       end if;
       
       
     end process;
     
     -- 60x80 (3Cx50) 
     -- 0 --- 4F
     -- .......   
     -- .......   
     -- 3B -- 4F
     
     mem_web <= '1';
     -- row = 011000 (24), col = 0110000(48)
     mem_wdata <= (others=>'1') when row < X"1" or row > X"3A" else
                  (others => '1') when col > X"4E" else (others => '0');
   
     mem_waddr <= row & col;
                  
   -- ModuleWare code(v1.9) for instance 'U_1' of 'inv'
   rst <= NOT(KEY(0));

   -- Instance port mappings.
   U_0 : Display_IF
      PORT MAP (
         clk        => CLOCK_27,
         mem_waddr  => mem_waddr,
         mem_wdata  => mem_wdata,
         mem_web    => mem_web,
         rst        => rst,
         VGA_B      => VGA_B,
         VGA_BLANK  => VGA_BLANK,
         VGA_CLK    => VGA_CLK,
         VGA_G      => VGA_G,
         VGA_H_SYNC => VGA_HS,
         VGA_R      => VGA_R,
         VGA_SYNC   => VGA_SYNC,
         VGA_V_SYNC => VGA_VS
      );

END struct;
